import * as colors from './colors';

export const themeLight = {
  dark: false,
  colors: {
    primary: colors.blue,
    background: colors.white,
    card: colors.white,
    text: colors.darkBlue,
    border: colors.gray2,
    error: colors.red,
    success: colors.green,
    warning: colors.orange,
    waiting: colors.yellow,
    disable: colors.gray6,
    secondaryCard: colors.gray1,
    thirdCard: colors.gray1,
    secondaryBorder: colors.gray1,
    secondaryBackground: colors.gray6,
    thirdBackground: colors.gray6,
    forthBackground: colors.gray1,
    secondaryText: colors.gray4,
    secondaryTab: colors.gray4,
    thirdText: colors.gray3,
    modal: colors.white,
    chevronRight: colors.black,
    black: colors.black,
    primary: colors.darkBlue,
    secondary: colors.lightGray,
    tertiary: colors.lightBlue,
    darkRed: colors.darkRed,
    darkGrey: colors.darkGrey,
    darkYellow: colors.darkYellow,
    white : colors.white,
    red: colors.red,
    inputBackground: colors.inputBackground,
    inputPlaceholder: colors.inputPlaceholder,
    inputBorder: colors.inputBorder,
  },
};

export const themeDark = {
  dark: true,
  colors: {
    primary: colors.blue,
    background: colors.gray10,
    card: colors.gray8,
    text: colors.gray11,
    border: colors.gray7,
    error: colors.red,
    success: colors.green,
    warning: colors.orange,
    waiting: colors.yellow,
    disable: colors.gray3,
    secondaryCard: colors.gray7,
    thirdCard: colors.gray8,
    secondaryBorder: colors.gray4,
    secondaryBackground: colors.gray5,
    thirdBackground: colors.gray10,
    secondaryText: colors.gray2,
    secondaryTab: colors.gray9,
    forthBackground: colors.gray5,
    thirdText: colors.gray3,
    modal: colors.gray7,
    chevronRight: colors.gray9,
    primary: colors.darkBlue,
    secondary: colors.lightGray,
    tertiary: colors.lightBlue,
  },
};
